version: '2.4'


services:
  db:
    image: postgres:13
    hostname: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: woc
    ports:
      - 5434:5432
    restart: always
    volumes:
      - ../workout_calendar_data/woc_db:/var/lib/postgresql/data
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py --reload
    environment:
      DB_URL: postgresql://user:password@db:5432/woc
      ASYNC_DB_URL: postgresql+asyncpg://user:password@db:5432/woc
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8081:8000"
    depends_on:
      - db


  front:
    build:
      context: frontend
      dockerfile: Dockefile
    volumes:
      - ./frontend:/app
    command: yarn serve --host 0.0.0.0 --port 8080
    ports:
      - "127.0.0.1:8080:8080"
