"""empty message

Revision ID: 8e644dac55c7
Revises: 73e3a22d181c
Create Date: 2022-02-10 17:15:56.244995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e644dac55c7'
down_revision = '73e3a22d181c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('access_token', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.drop_index('ix_token_token', table_name='token')
    op.create_index(op.f('ix_token_access_token'), 'token', ['access_token'], unique=True)
    op.drop_column('token', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_token_access_token'), table_name='token')
    op.create_index('ix_token_token', 'token', ['token'], unique=False)
    op.drop_column('token', 'access_token')
    # ### end Alembic commands ###
