"""empty message

Revision ID: d61d7c9f7023
Revises: 8e644dac55c7
Create Date: 2022-02-14 17:03:18.010337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'd61d7c9f7023'
down_revision = '8e644dac55c7'
branch_labels = None
depends_on = None


def upgrade():
    user = table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('day', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_day_user_id'), 'day', ['user_id'], unique=False)
    op.create_foreign_key('day_user_id_fkey', 'day', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedule', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schedule_user_id'), 'schedule', ['user_id'], unique=False)
    op.create_foreign_key('schedule_user_id_fkey', 'schedule', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('training_day_type', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_day_type_user_id'), 'training_day_type', ['user_id'], unique=False)
    op.create_foreign_key('training_day_type_user_id_fkey', 'training_day_type', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    op.execute('''insert into "user"("id","name","hashed_password","is_active") 
    values(
        1,
        'user',
        'kDPaIOclhPqN$becc82eb2371f4729ef23cd2148bd54790ad5a0306c751904d6137eb5812560b',
        true
    ) ON CONFLICT DO NOTHING ''')
    op.execute('update day set user_id = 1 where user_id is null')
    op.execute('update schedule set user_id = 1 where user_id is null')
    op.execute('update training_day_type set user_id = 1 where user_id is null')

    op.alter_column('day', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('schedule', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('training_day_type', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('user_user_uniq', 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_uniq', 'user', type_='unique')
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint('training_day_type_user_id_fkey', 'training_day_type', type_='foreignkey')
    op.drop_index(op.f('ix_training_day_type_user_id'), table_name='training_day_type')
    op.drop_column('training_day_type', 'user_id')
    op.drop_constraint('schedule_user_id_fkey', 'schedule', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_user_id'), table_name='schedule')
    op.drop_column('schedule', 'user_id')
    op.drop_constraint('day_user_id_fkey', 'day', type_='foreignkey')
    op.drop_index(op.f('ix_day_user_id'), table_name='day')
    op.drop_column('day', 'user_id')
    op.drop_column('day', 'details')
    # ### end Alembic commands ###
